### ISSUE TITLE
"Content with characters ', " or & may need to be escaped with three brackets" unnecesary warning

### ISSUE THREAD

**Issue by noway** [sendgrid/sendgrid-nodejs#965]
#### Issue Summary

```Content with characters ', " or & may need to be escaped with three brackets``` is logged even if I have {{{ 3 brackets in the templates

The bug has been introduced here: https://github.com/sendgrid/sendgrid-nodejs/issues/790

I'm trying to keep my logs clean so that i can grep them and look at them, and this seems to be quite a thing which pops out unnecessarily. I also use my own debug.js-based logger, so a wild console.log is something that straight away goes against my logging policies. I appreciate the warning, but after I fixed the handlebars template it is still complaining to me.

#### Steps to Reproduce

1. Try to send any email with dynamicTemplate prop which have any of those characters

#### Technical details:

* sendgrid-nodejs Version: 6.4.0
* Node.js Version: 12.6

**Comment by ErwinAI** [comment]
I am having this problem as well and would like this to change for the same reasons as @noway mentioned. I did see a function called 'setHideWarnings' in the helper, but not sure how to use this.

**Comment by broofa** [comment]
FWIW, #932 adds a `hideWarning` flag that can be used to suppress this.  See https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/hide-warnings.md
... however this is not yet published (still!)

@thinkingserious The above not withstanding, #790 and #932 should both be reverted because, frankly, this feature is completely broken as it stands.

- There is no explanation of why the warning is logged (the [explanatory URL](https://sendgrid.com/docs/ui/sending-email/using-handlebars/) is 404'ing)
- There is no indication of which dynamic token contains the problematic characters
- The warning occurs _**even if there's no problem**_, so not only do you get a warning if you're doing things correctly, but even if you're doing them wrong and you fix the problem, _you still get the warning._ :-(

Fundamentally, the problem here is that the JS client code doesn't have enough information to know whether a problem actually exists. It needs to know which tokens are triple-bracket escaped in the template, and exempt those from the warning test.   Because it doesn't have this information, the client is being overly aggressive with it's warnings, which creates a headache for any developers that like to have clean logs (which is pretty much all of them.)

Either sendgrid needs to provide that information to the client (somehow), or this warning should be moved to the server and done as part of the message validation there.

My $.02.

**Comment by dockleryxk** [comment]
@broofa just so you know, I have templates that use _exclusively_ triple brackets. I still get this warning!

**Comment by thakichowdhury** [comment]
I'm experiencing the same thing. We have automated check-in/confirmation emails and these warnings are polluting our server logs.

**Comment by broofa** [comment]
@brandt  Sorry to bother you, but is there anyone from @sendgrid triaging these issues?

**Comment by andresmijares** [comment]
have anyone found a solution for this?

**Comment by ErwinAI** [comment]
@broofa It seems like that is not the case. I'll try to reach out to dx@sendgrid.com to see if a new release can be made.

**Comment by dockleryxk** [comment]
@ErwinAI thank you for this. If you hear anything back please let us know.

**Comment by LukeXF** [comment]
I'm also facing this issue, did you get anything back from them @ErwinAI?

**Comment by 3sanket3** [comment]
Is it just a warning? I my case it's error. It breaks the code and not sending the email?

**Comment by jamielob** [comment]
We still have this polluting our logs, also in some templates that exclusively use triple brackets.   Anyone seen any fixes for this being worked on?

**Comment by childish-sambino** [comment]
Fixed by #932 which was included in the 6.5.0 release.

**Comment by adamreisnz** [comment]
Well this sent me off on a wild goose chase, trying to find faulty characters.... >.<

**Comment by Kostanos** [comment]
@sendgrid/mail": "^7.2.5
Still have this issue, am I using a different library? any recommendations?

**Comment by childish-sambino** [comment]
@Kostanos Are you hiding the warnings? https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/hide-warnings.md

**Comment by LukeXF** [comment]
I added `hideWarning: true` and this hid the warning, but I would like to know why the warning is showing up in the first place? All my templates have `{{{ }}}` so I don't think the warning handling is correct?

Is anyone able to shed some light on this?

**Comment by AngelFHC** [comment]
Warning still showing up as of version 7.6.0

Using only one instance of triple handlebars (none doble) on a dynamic template, but perhaps it's the specific use case?

```
<a href="{{{link_string}}}">
  Click here
</a>
```

```
<a href="{{{link_string}}}">
  Click here
</a>```
